// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB43NQ7Ufp5_PyL_IoycO9S5Bu9Bg3uJeI',
    appId: '1:341438559546:web:a5c5a6161be6d388340c03',
    messagingSenderId: '341438559546',
    projectId: 'chiragdemoflutter',
    authDomain: 'chiragdemoflutter.firebaseapp.com',
    databaseURL: 'https://chiragdemoflutter-default-rtdb.firebaseio.com',
    storageBucket: 'chiragdemoflutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1PaI3y6xYB53IuEN65AeIkuyVGAgLVIk',
    appId: '1:341438559546:android:1311c881c6dfd580340c03',
    messagingSenderId: '341438559546',
    projectId: 'chiragdemoflutter',
    databaseURL: 'https://chiragdemoflutter-default-rtdb.firebaseio.com',
    storageBucket: 'chiragdemoflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXRuSEjhPBvi1zjrwdC5j29QIN0b1XYUA',
    appId: '1:341438559546:ios:38aea1301c729e3e340c03',
    messagingSenderId: '341438559546',
    projectId: 'chiragdemoflutter',
    databaseURL: 'https://chiragdemoflutter-default-rtdb.firebaseio.com',
    storageBucket: 'chiragdemoflutter.appspot.com',
    androidClientId: '341438559546-9de1srom2bsnnt12ln9oqbm4117vgkac.apps.googleusercontent.com',
    iosClientId: '341438559546-jaqjoatpa07dvdfvhg2dg09df4c2okbv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPracticeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXRuSEjhPBvi1zjrwdC5j29QIN0b1XYUA',
    appId: '1:341438559546:ios:38aea1301c729e3e340c03',
    messagingSenderId: '341438559546',
    projectId: 'chiragdemoflutter',
    databaseURL: 'https://chiragdemoflutter-default-rtdb.firebaseio.com',
    storageBucket: 'chiragdemoflutter.appspot.com',
    androidClientId: '341438559546-9de1srom2bsnnt12ln9oqbm4117vgkac.apps.googleusercontent.com',
    iosClientId: '341438559546-jaqjoatpa07dvdfvhg2dg09df4c2okbv.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPracticeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB43NQ7Ufp5_PyL_IoycO9S5Bu9Bg3uJeI',
    appId: '1:341438559546:web:a93e5f93eeb51082340c03',
    messagingSenderId: '341438559546',
    projectId: 'chiragdemoflutter',
    authDomain: 'chiragdemoflutter.firebaseapp.com',
    databaseURL: 'https://chiragdemoflutter-default-rtdb.firebaseio.com',
    storageBucket: 'chiragdemoflutter.appspot.com',
  );
}
